window:
  height: 500
  width: 800
player_one:
  color:
    red: 0
    green: 0
    blue: 255
  hue:
    min: 90
    max: 128
player_two:
  color:
    red: 255
    green: 0
    blue: 0
  hue:
    min: 159
    max: 180
fake_background: true
show_markers: true
